Table cbo {
	 codigo int4 [pk]
	 titulo varchar
	 valor varchar
	 id int4
}

Table classificacao_final {
	 id int4 [pk]
	 classificacao_final varchar
}

Table criterio_classificacao {
	 id int4 [pk]
	 criterio_classificacao varchar
}

Table escolaridade {
	 id int2 [pk]
	 escolaridade varchar
}

Table estado {
	 co_uf varchar [pk]
	 no_completo_uf varchar
	 sg_uf varchar
	 no_uf varchar
}

Table etnia {
	 co_etnia int4 [pk]
	 etnia varchar
}

Table evolucao {
	 id int4 [pk]
	 evolucao varchar
}

Table febre {
	 id int4 [pk]
	 febre varchar
}

Table metodo {
	 id varchar [pk]
	 metodo varchar
}

Table municipio {
	 co_municipio varchar [pk]
	 nu_longitude varchar
	 pop_10_14 int4
	 co_macro_reg varchar
	 pop_80 int4
	 pop_15_19 int4
	 co_regional varchar
	 pop_70_79 int4
	 pop_60_69 int4
	 pop_0_4 int4
	 pop_20_29 int4
	 no_municipio varchar
	 no_municipio_completo varchar
	 co_uf varchar
	 pop_40_49 int4
	 nu_latitude varchar
	 pop_50_59 int4
	 pop_5_9 int4
	 pop_30_39 int4
	 populacao int4
}

Table pais {
	 co_pais varchar [pk]
	 ds_pais varchar
}

Table periodo_gestacao {
	 id int4 [pk]
	 periodo_gestacao varchar
}

Table raca_cor {
	 id int4 [pk]
	 raca_cor varchar
}

Table raiox_torax {
	 id int4 [pk]
	 raiox_torax varchar
}

Table resultado {
	 id int4 [pk]
	 resultado varchar
}

Table sexo {
	 id int4 [pk]
	 sexo varchar
}

Table sim_nao {
	 id int4 [pk]
	 sim_nao varchar
}

Table tipo_internacao {
	 id int4 [pk]
	 tipo_internacao varchar
}

Table tipo_paciente {
	 id int4 [pk]
	 tipo_paciente varchar
}

Table uso_antiviral {
	 id int4 [pk]
	 uso_antiviral varchar
}

Table notificacao {
	 criterio_classificacao int4 [ref: - criterio_classificacao.id]
	 evolucao int4 [ref: - evolucao.id]
	 raca_cor int4 [ref: - raca_cor.id]
	 perda_olfato_paladar int4 [ref: - sim_nao.id]
	 cod_cbo int4 [ref: - cbo.codigo]
	 escolaridade int4 [ref: - escolaridade.id]
	 id int4 [pk]
	 tipo_paciente int4 [ref: - tipo_paciente.id]
	 etnia int4 [ref: - etnia.co_etnia]
	 sexo int4 [ref: - sexo.id]
	 idade int4 
	 gestante int4 [ref: - sim_nao.id]
	 periodo_gestacao int4 [ref: - periodo_gestacao.id]
	 febre int4 [ref: - febre.id]
	 tosse int4 [ref: - sim_nao.id]
	 dor_garganta int4 [ref: - sim_nao.id]
	 mialgia int4 [ref: - sim_nao.id]
	 artralgia int4 [ref: - sim_nao.id]
	 diarreia int4 [ref: - sim_nao.id]
	 nausea_vomitos int4 [ref: - sim_nao.id]
	 cefaleia int4 [ref: - sim_nao.id]
	 coriza int4 [ref: - sim_nao.id]
	 irritabilidade_confusao int4 [ref: - sim_nao.id]
	 adinamia int4 [ref: - sim_nao.id]
	 escarro int4 [ref: - sim_nao.id]
	 calafrios int4 [ref: - sim_nao.id]
	 data_cadastro date 
	 data_1o_sintomas date 
	 data_liberacao date 
	 data_recebimento date 
	 data_isolamento date 
	 data_coleta date 
	 data_retorno_local date 
	 data_chegada_estado date 
	 data_nascimento date 
	 data_encerramento date 
	 data_entrada date 
	 data_cura_obito date 
	 data_alta date 
	 data_ida_local date 
	 data_chegada_brasil date 
	 updated_at timestamp 
	 data_notificacao timestamp 
	 data_confirmacao timestamp 
	 congestao_nasal int4 [ref: - sim_nao.id]
	 congestao_conjuntiva int4 [ref: - sim_nao.id]
	 dificuldade_deglutir int4 [ref: - sim_nao.id]
	 manchas_vermelhas int4 [ref: - sim_nao.id]
	 ganglios_linfaticos int4 [ref: - sim_nao.id]
	 asas_nasais int4 [ref: - sim_nao.id]
	 saturacao_o2 int4 [ref: - sim_nao.id]
	 cianose int4 [ref: - sim_nao.id]
	 tiragem_intercostal int4 [ref: - sim_nao.id]
	 dispneia int4 [ref: - sim_nao.id]
	 raiox_torax int4 [ref: - raiox_torax.id]
	 tomografia int4 [ref: - sim_nao.id]
	 doenca_cardiovascular int4 [ref: - sim_nao.id]
	 hipertensao int4 [ref: - sim_nao.id]
	 diabetes int4 [ref: - sim_nao.id]
	 doenca_hepatica int4 [ref: - sim_nao.id]
	 doenca_neurologica int4 [ref: - sim_nao.id]
	 sindrome_down int4 [ref: - sim_nao.id]
	 imunodeficiencia int4 [ref: - sim_nao.id]
	 infeccao_hiv int4 [ref: - sim_nao.id]
	 doenca_renal int4 [ref: - sim_nao.id]
	 doenca_pulmonar int4 [ref: - sim_nao.id]
	 neoplasia int4 
	 puerperio int4 [ref: - sim_nao.id]
	 obesidade int4 [ref: - sim_nao.id]
	 tabagismo int4 [ref: - sim_nao.id]
	 hospitalizado int4 [ref: - sim_nao.id]
	 internacao_sus int4 [ref: - sim_nao.id]
	 tipo_internacao int4 [ref: - tipo_internacao.id]
	 uso_antiviral int4 [ref: - uso_antiviral.id]
	 coleta_amostra int4 [ref: - sim_nao.id]
	 resultado int4 [ref: - resultado.id]
	 historico_viagem int4 [ref: - sim_nao.id]
	 classificacao_final int4 [ref: - classificacao_final.id]
	 local_viagem text 
	 outras_morbidades text 
	 outros_sintomas text 
	 requisicao varchar 
	 metodo varchar [ref: - metodo.id]
	 lab_executor varchar 
	 nome_unidade_notifica varchar 
	 uf_unidade_notifica varchar [ref: - estado.co_uf]
	 ibge_unidade_notifica varchar [ref: - municipio.co_municipio]
	 nome_notificador varchar 
	 email_notificador varchar 
	 telefone_notificador varchar 
	 numero_do varchar 
	 pais_residencia varchar [ref: - pais.co_pais]
	 cpf varchar 
	 paciente varchar 
	 nome_mae varchar 
	 uf_residencia varchar [ref: - estado.co_uf]
	 ibge_residencia varchar [ref: - municipio.co_municipio]
	 cep_residencia varchar 
	 logradouro_residencia varchar 
	 numero_residencia varchar 
	 bairro_residencia varchar 
}

