SELECT  nt.id,
        to_char(nt.data_notificacao,'DD/MM/YYYY') AS data_notificacao,
		nt.etnia,
        nt.paciente,
        nt.sexo,
        to_char(nt.data_nascimento,'DD/MM/YYYY') AS data_nascimento,
		nt.idade,
        nt.nome_mae,
        nt.raca_cor,
        nt.uf_residencia,
        nt.ibge_residencia,
		nt.nome_notificador,
		nt.email_notificador,
		nt.telefone_notificador,
		nt.nome_unidade_notifica,
        nt.uf_unidade_notifica,
        nt.ibge_unidade_notifica,
		-- nt.origem, # SISTEMAS?
        to_char(nt.data_liberacao,'DD/MM/YYYY') AS data_liberacao,
		-- nt.requisicao,
		nt.resultado,
		-- nt.exame,
		-- nt.metodo,
		-- nt.lab_executor,
        nt.evolucao,
        to_char(nt.data_cura_obito,'DD/MM/YYYY') AS data_cura_obito,
        to_char(nt.updated_at,'DD/MM/YYYY') AS updated_at
		-- nt.numero_do,
		-- nt.rash_paciente,
		-- nt.rash_paciente_1,
		-- nt.rash_paciente_2,
  FROM  public.notificacao nt
  WHERE nt.classificacao_final = '2' AND nt.excluir_ficha = '2' AND (nt.status_notificacao = '1' OR nt.status_notificacao = '2')
ORDER BY 1;